[package]
name = "pge"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pge-core = { path = "../pge-core" }
pge-physics = { path = "../pge-physics" }
pge-renderer = { path = "../pge-renderer" }
pge-wgpu-renderer = { path = "../pge-wgpu-renderer", optional = true }
pge-video = { path = "../pge-video" }
pge-app = { path = "../pge-app" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"]  }
rand = "0.8"

[features]
wgpu_winit = []
wgpu_renderer = ["pge-wgpu-renderer"]


[[bench]]
name = "bench_main"
harness = false

[[bin]]
name = "cube_falls_to_floor"
required-features = ["wgpu_winit"]
